# Generated by Django 2.2.5 on 2019-10-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_donation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationmodel',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='institutionmodel',
            name='type',
            field=models.CharField(choices=[('org', 'organizacja pozarządowa'), ('fund', 'fundacja'), ('local', 'zbiórka lokalna')], default='fund', max_length=6),
        ),
    ]
