# Generated by Django 2.2.5 on 2019-09-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_donation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationmodel',
            old_name='quantity',
            new_name='bag_quantity',
        ),
        migrations.AlterField(
            model_name='institutionmodel',
            name='type',
            field=models.CharField(choices=[('fund', 'fundacja'), ('org', 'organizacja pozarządowa'), ('local', 'zbiórka lokalna')], default='fund', max_length=6),
        ),
    ]
